# Generated by Django 2.2.7 on 2020-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='herb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb_name', models.CharField(max_length=10000)),
                ('img', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
